Integer = int(input("Enter integer : \n"))
print(f"You entered : {Integer}")
print(f"{Integer} squared is {Integer**2}!!")
print(f"And {Integer} cubed is {Integer**3}!!")
Integer2 = int(input("Enter another integer : \n"))
print(f"{Integer} + {Integer2} is {Integer+Integer2}")
print(f"{Integer} * {Integer2} is {Integer*Integer2}")
